# Generated by Django 4.1.6 on 2023-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автора книги', null=True, to='catalog.author', verbose_name='Aвтop книги'),
        ),
    ]
